spring.application.name=smartstock-system

# Globales Level
logging.level.root=INFO

# Spezifisch für Ihr System
logging.level.org.example.smartstocksystem=DEBUG

# Optional: In Datei schreiben
logging.file.name=logs/smartstock.log

spring.datasource.url=jdbc:postgresql://localhost:5432/smartstock
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true