INSERT INTO products (name, stock, min_threshold) VALUES
                                                      ('Schrauben M6 x 20mm',        150,  20),
                                                      ('Schrauben M8 x 30mm',         80,  15),
                                                      ('Muttern M6',                 200,  30),
                                                      ('Muttern M8',                 120,  25),
                                                      ('Unterlegscheiben M6',        300,  40),
                                                      ('Unterlegscheiben M8',        250,  35),
                                                      ('Holzleim 500ml',              45,  10),
                                                      ('Silikon transparent 300ml',   30,   8),
                                                      ('Kabelbinder 100er Pack',      60,  10),
                                                      ('Klebeband 50m',               40,  10),
                                                      ('Bohrer 6mm HSS',              25,   5),
                                                      ('Bohrer 8mm HSS',              18,   5),
                                                      ('Bohrer 10mm HSS',             12,   5),
                                                      ('Sägeblatt 180mm',             15,   3),
                                                      ('Schleifpapier K80 10er',      50,  10),
                                                      ('Schleifpapier K120 10er',     45,  10),
                                                      ('Schleifpapier K240 10er',     30,  10),
                                                      ('Hammer 500g',                 20,   5),
                                                      ('Hammer 1000g',                10,   3),
                                                      ('Schraubenzieher PH2',         35,   8),
                                                      ('Schraubenzieher PH1',         28,   8),
                                                      ('Schraubenzieher Schlitz 5mm', 22,   8),
                                                      ('Zange Kombizange 180mm',      15,   4),
                                                      ('Zange Spitzzange 160mm',      12,   4),
                                                      ('Wasserwaage 60cm',             8,   2),
                                                      ('Wasserwaage 120cm',            5,   2),
                                                      ('Maßband 5m',                  25,   5),
                                                      ('Maßband 10m',                 18,   5),
                                                      ('Steckdosenleiste 5-fach',     20,   4),
                                                      ('Verlängerungskabel 10m',      12,   3),
                                                      ('Kabeltrommel 25m',             6,   2),
                                                      ('Arbeitshandschuhe Gr. L',     40,  10),
                                                      ('Arbeitshandschuhe Gr. M',     35,  10),
                                                      ('Schutzbrille klar',           30,   8),
                                                      ('Staubmaske FFP2 10er',        55,  15),
                                                      ('Gehörschutz',                 20,   5),
                                                      ('Farbrolle 18cm',              25,   6),
                                                      ('Pinsel 5cm',                  30,   8),
                                                      ('Abdeckfolie 4x5m',            15,   4),
                                                      ('Malerkrepp 50m',              40,  10),
                                                      ('Dispersionsfarbe weiß 10L',   10,   3),
                                                      ('Holzlasur nussbaum 750ml',     8,   2),
                                                      ('Wanddübel S6 100er',         180,  30),
                                                      ('Wanddübel S8 100er',         150,  25),
                                                      ('Nagel 50mm 500g',            100,  20),
                                                      ('Nagel 80mm 500g',             80,  20),
                                                      ('Bauschaum 750ml',             22,   5),
                                                      ('Fugenmasse weiß 300ml',       18,   5),
                                                      ('Reinigungsspray 500ml',       35,   8),
                                                      ('Werkzeugkoffer leer 40cm',     7,   2);